export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

export const ACCOUNT_CONFIRMATION_SUCCESS = "ACCOUNT_CONFIRMATION_SUCCESS";
export const ACCOUNT_CONFIRMATION_FAIL = "ACCOUNT_CONFIRMATION_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_CURRENTUSER = "GET_CURRENTUSER";